# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-28 06:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_registered_appointments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.RemoveField(
            model_name='registered_appointments',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='registered_appointments',
        ),
    ]
