# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_auto_20171005_0833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Unregistered_Patients',
        ),
    ]
